export const FETCH_CITIES = 'FETCH_CITIES';
export const FILTER_CITIES = 'FILTER_CITIES';
export const GET_STATIONS = 'GET_STATIONS';
export const DISPLAY_ERROR = 'DISPLAY_ERROR';
export const RESET_ERROR = 'RESET_ERROR';